name: Create Branch on Issue Assignment

on:
  issues:
    types: [assigned]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create new branch
        run: |
          BRANCH_NAME=issue-${{ github.event.issue.number }}
          git checkout develop
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
